In [1]:
#Create a null vector of size 10 but the fifth value which is 1.
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
 #Create a vector with values ranging from 10 to 49.

import numpy as np
vector_10_to_49 = np.arange(10, 50)
print(vector_10_to_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


In [5]:
#Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)



Minimum value: 0.011966786392207274
Maximum value: 0.995819813139176


In [6]:
#Create a random vector of size 30 and find the mean value.
import numpy as np
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:")
print(random_vector)
print("\nMean value:", mean_value)


Random Vector:
[0.69751198 0.9880473  0.81463407 0.04179691 0.05415166 0.60730483
 0.61212058 0.77483437 0.70457376 0.86427642 0.87337646 0.14984428
 0.8948836  0.3110886  0.17058955 0.28014438 0.57508939 0.20589873
 0.34805591 0.15409371 0.30995173 0.30902704 0.91346586 0.75366325
 0.57402309 0.39348426 0.47371458 0.91488738 0.68991709 0.13571452]

Mean value: 0.519672175305749
